const express=require('express');
const path=require('path');
const app=express(); const PORT=process.env.PORT||3000;
app.use(express.json({limit:'100kb'})); app.use(express.static(__dirname));
const BOX={1800:15,2800:30,3800:40,4800:60,5800:90,9800:150};
const SHIPPING={1800:15,2800:20,3800:25,4800:35,5800:50,9800:95};
const BRANDS={'Customer Supplied':0,'Kenwood':40,'Pyle':40,'Skar Audio':50,'Pioneer':50,'Boss Audio':50,'DS18':60,'Memphis Audio':75,'Kicker':80,'JBL':80,'Infinity':80,'Rockford Fosgate':90,'Wet Sounds':150,'JL Audio':180};
const SUB_BRANDS={'Kicker':120,'Rockford Fosgate':130,'JBL':110,'DS18':100,'Skar Audio':90,'Memphis Audio':130,'Wet Sounds':250,'JL Audio':250,'Kenwood':100,'Pioneer':100,'Infinity':110,'Boss Audio':50,'Pyle':40,'Customer Supplied':0};
const POWER={'Include Battery and Charger Bundle':60,'DeWalt 20V':15,'Milwaukee M18':15,'Hart 20V':15,'Ryobi 18V':15,'Makita 18V':15,'Other':15};
function val(b,k){return b?.selections?.[k]?.value??''}
function caseCode(build){return String(val(build,'case')).match(/1800|2800|3800|4800|5800|9800/)?.[0]||''}
function calculate(build){let total=0;const box=caseCode(build);if(!(box in BOX))throw new Error('Invalid box selection.');total+=BOX[box];if(val(build,'color')==='Custom')total+=25;const count=Number((val(build,'count').match(/\d+/)||['0'])[0]);if(!count)throw new Error('Invalid speaker count.');const brand=val(build,'brand');if(!(brand in BRANDS))throw new Error('Invalid speaker brand.');total+=BRANDS[brand]*count/2;const sub=val(build,'sub')==='Yes';const subCount=val(build,'subCount')==='2 Subwoofers'?2:(sub?1:0);if(sub){const sb=val(build,'subBrand');if(!(sb in SUB_BRANDS))throw new Error('Invalid subwoofer brand.');total+=SUB_BRANDS[sb]*subCount}const power=val(build,'power');if(!(power in POWER))throw new Error('Invalid power selection.');total+=POWER[power];total+=Number((val(build,'tweeters').match(/\d+/)||['0'])[0])*10;const extra=val(build,'extra');const extras=extra==='None'?[]:extra.split(' + ').filter(Boolean);if(extras.includes('Battery Voltage and Charging Port'))total+=25;if(extras.includes('Custom Name / Logo'))total+=20;total+=Math.ceil(count/2)*25+subCount*25;return Math.round(total)}
function shipping(build){const c=caseCode(build);if(!(c in SHIPPING))throw new Error('Unable to calculate shipping.');return SHIPPING[c]}
async function accessToken(){const id=process.env.PAYPAL_CLIENT_ID,secret=process.env.PAYPAL_CLIENT_SECRET;if(!id||!secret)throw new Error('PayPal is not connected yet. Add PAYPAL_CLIENT_ID and PAYPAL_CLIENT_SECRET to the server environment.');const base=process.env.PAYPAL_ENV==='live'?'https://api-m.paypal.com':'https://api-m.sandbox.paypal.com';const r=await fetch(base+'/v1/oauth2/token',{method:'POST',headers:{Authorization:'Basic '+Buffer.from(id+':'+secret).toString('base64'),'Content-Type':'application/x-www-form-urlencoded'},body:'grant_type=client_credentials'});const j=await r.json();if(!r.ok)throw new Error(j.error_description||'PayPal authentication failed.');return {token:j.access_token,base}}
app.get('/api/paypal/config',(req,res)=>{const id=process.env.PAYPAL_CLIENT_ID;if(!id)return res.status(500).json({error:'PayPal client ID is not configured.'});res.json({clientId:id,env:process.env.PAYPAL_ENV==='live'?'live':'sandbox'})});
app.post('/api/paypal/orders',async(req,res)=>{try{const {customer,build}=req.body||{};if(!customer?.name||!customer?.email||!customer?.phone||!customer?.address1||!customer?.city||!customer?.state||!customer?.zip||!build)throw new Error('Missing customer, shipping, or build information.');const subtotal=calculate(build),ship=shipping(build),grand=subtotal+ship;const {token,base}=await accessToken();const site=process.env.PUBLIC_URL||`${req.protocol}://${req.get('host')}`;const compact=Object.values(build.selections||{}).map(x=>x.value).filter(Boolean).join(' | ').slice(0,120);const body={intent:'CAPTURE',purchase_units:[{description:'Built2BoomCustoms Custom Speaker Build',custom_id:compact,amount:{currency_code:'USD',value:grand.toFixed(2),breakdown:{item_total:{currency_code:'USD',value:subtotal.toFixed(2)},shipping:{currency_code:'USD',value:ship.toFixed(2)}}},items:[{name:'Custom Speaker Build',quantity:'1',unit_amount:{currency_code:'USD',value:subtotal.toFixed(2)}}],shipping:{name:{full_name:customer.name},address:{address_line_1:customer.address1,address_line_2:customer.address2||undefined,admin_area_2:customer.city,admin_area_1:customer.state.toUpperCase(),postal_code:customer.zip,country_code:'US'}}}]};const r=await fetch(base+'/v2/checkout/orders',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json','PayPal-Request-Id':'b2b-'+Date.now()},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.message||'Unable to create PayPal order.');res.json({orderId:j.id,subtotal,shipping:ship,total:grand})}catch(e){res.status(400).json({error:e.message||'Unable to create payment.'})}});
app.post('/api/paypal/orders/:orderID/capture',async(req,res)=>{try{const orderID=req.params.orderID;if(!orderID)throw new Error('Missing PayPal order ID.');const {token,base}=await accessToken();const r=await fetch(`${base}/v2/checkout/orders/${encodeURIComponent(orderID)}/capture`,{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'}});const j=await r.json();if(!r.ok)throw new Error(j.message||'Payment capture failed.');res.json(j)}catch(e){res.status(400).json({error:e.message||'Payment could not be completed.'})}});
app.get('/api/paypal/capture',async(req,res)=>{try{const orderID=req.query.token;if(!orderID)throw new Error('Missing PayPal order ID.');const {token,base}=await accessToken();const r=await fetch(`${base}/v2/checkout/orders/${encodeURIComponent(orderID)}/capture`,{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'}});const j=await r.json();if(!r.ok)throw new Error(j.message||'Payment capture failed.');res.redirect('/success.html?order_id='+encodeURIComponent(orderID))}catch(e){res.status(400).send('Payment could not be completed: '+e.message)}});
app.listen(PORT,()=>console.log(`Built2BoomCustoms running on ${PORT}`));
